server:
  port: 8801

spring:
  application:
    name: stream-rabbitmq-provider
  cloud:
    stream:
      # 配置绑定的mq服务信息
      binders:
        # 自定义的服务设置名称,应用于binding的整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          # 设置rabbitmq相关环境
          environment:
            spring:
              rabbitmq:
                host: 47.94.245.17
                port: 5672
                username: test
                password: test
                virtual-host: /cloud_learn
      #服务整合处理
      bindings:
        # 这个名字是一个通道名字 output 消息接受
        output:
          # 使用交换机的名称
          destination: cloud2020
          # 设置消息数据类型
          content-type: application/json
          # 设置绑定的服务设置名称
          binder: defaultRabbit


eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认是true
    register-with-eureka: true
    #是否将EurekaServer抓取已有的注册信息,默认是true,单节点无所谓,但集群必须设置为true才能配和ribbon使用均衡负债
    fetch-registry: true
    service-url:
      #Eureka注册地址
      #defaultZone: http://localhost:7001/eureka
      #集群环境
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #修改在eureka上显示的服务名称
    instance-id: sender8801
    #访问路径是否显示ip地址
    prefer-ip-address: true
    #eureka向服务端发送心跳时间间隔,单位为秒 默认是30秒
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端在最后一次心跳后的等待时间上限,单位为秒,默认90秒,超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
