server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能,利用微服务名进行路由
          enabled: true
      routes:
          # 路由ID
        - id: payment_8007
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8007
          #lb均衡负载LoadBalance的缩写
          uri: lb://cloud-payment-service
          predicates:
              # 断言,路径相匹配后输出
            - Path=/payment/**

        # 路由ID
        - id: order_hystrix
          # 匹配后提供服务的路由地址
          uri: http://localhost:80
          predicates:
            # 断言,路径相匹配后输出
            - Path=/order/**
            # 时间过滤条件
            #- After=2020-10-17T21:57:42.541+08:00[Asia/Shanghai]
            # cookie过滤条件 curl http://127.0.0.1:9527/order/getPayment/2 --cookie "username=jacques"
            #- Cookie=username,jacques
            # header过滤条件 curl http://127.0.0.1:9527/order/getPayment/2 --cookie "username=jacques" -H "token:2"
            #- Header=token,\S
            # 访问主机过滤条件
            #- Host=localhost
            # 其他过滤条件 Query 访问条件 , Method  请求类型
eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认是true
    register-with-eureka: true
    #是否将EurekaServer抓取已有的注册信息,默认是true,单节点无所谓,但集群必须设置为true才能配和ribbon使用均衡负债
    fetch-registry: true
    service-url:
      #Eureka注册地址
      #defaultZone: http://localhost:7001/eureka
      #集群环境
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service
    #修改在eureka上显示的服务名称
    instance-id: gateway9527
    #访问路径是否显示ip地址
    prefer-ip-address: true
    #eureka向服务端发送心跳时间间隔,单位为秒 默认是30秒
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端在最后一次心跳后的等待时间上限,单位为秒,默认90秒,超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
