server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    #表示自己不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心,职责就是维护服务实例,不需要去检索服务
    fetch-registry: false
    #设置与Eureka Server交互的地址查询服务和注册服务都需要以来这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
