server:
  port: 8007

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认是true
    register-with-eureka: true
    #是否将EurekaServer抓取已有的注册信息,默认是true,单节点无所谓,但集群必须设置为true才能配和ribbon使用均衡负债
    fetch-registry: true
    service-url:
      #Eureka注册地址
      #defaultZone: http://localhost:7001/eureka
      #集群环境
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #修改在eureka上显示的服务名称
    instance-id: payment8007
    #访问路径是否显示ip地址
    prefer-ip-address: true
    #eureka向服务端发送心跳时间间隔,单位为秒 默认是30秒
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端在最后一次心跳后的等待时间上限,单位为秒,默认90秒,超时将剔除服务
    #lease-expiration-duration-in-seconds: 2


mybatis-plus:
  configuration-properties:
    type-aliases-package: com.jacques.springcloud.entity
    mapper-locations: classpath:mapper/*.xml